runtime: nodejs8
instance_class: B2
manual_scaling:
  instances: 1

env_variables:
  REACT_APP_AUTH0_DOMAIN: project-memory-dev.eu.auth0.com
  REACT_APP_AUTH0_CLIENT_ID: SIhChd1c23UUtoDbeRdO1tOGZVo3qyid
  REACT_APP_AUTH0_CALLBACK: https://www.project-memory.org/callback
  REACT_APP_AUTH0_LOGOUT_CALLBACK: https://www.project-memory.org/logout
  REACT_APP_AUTH0_AUDIENCE: https://api.project-memory.org
  REACT_APP_API_ENDPOINT: https://api.project-memory.org
  REACT_APP_OAUTH_NAMESPACE: https://project-memory.com
  COOKIE_SECRET: Lisa is cute
  NODE_ENV: production
  DEBUG: app:*

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
