export const REACT_APP_API_ENDPOINT = "http://localhost:4000"
export const REACT_APP_AUTH0_LOGOUT_CALLBACK = "http://localhost:3000/logout"
export const REACT_APP_AUTH0_DOMAIN = "project-memory-dev.eu.auth0.com"
export const REACT_APP_AUTH0_CLIENT_ID = "SIhChd1c23UUtoDbeRdO1tOGZVo3qyid"
export const REACT_APP_AUTH0_CALLBACK = "http://localhost:3000/callback"
export const REACT_APP_AUTH0_AUDIENCE = "http://localhost:4000"
export const REACT_APP_API_URL = "http://localhost:4000"
